// Code generated by protoc-gen-go. DO NOT EDIT.
// source: audit.proto

package commonproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendLogRequest struct {
	Logs                 []byte   `protobuf:"bytes,1,opt,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendLogRequest) Reset()         { *m = SendLogRequest{} }
func (m *SendLogRequest) String() string { return proto.CompactTextString(m) }
func (*SendLogRequest) ProtoMessage()    {}
func (*SendLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5594839dd8e38a1b, []int{0}
}

func (m *SendLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendLogRequest.Unmarshal(m, b)
}
func (m *SendLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendLogRequest.Marshal(b, m, deterministic)
}
func (m *SendLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendLogRequest.Merge(m, src)
}
func (m *SendLogRequest) XXX_Size() int {
	return xxx_messageInfo_SendLogRequest.Size(m)
}
func (m *SendLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendLogRequest proto.InternalMessageInfo

func (m *SendLogRequest) GetLogs() []byte {
	if m != nil {
		return m.Logs
	}
	return nil
}

type AuditResponse struct {
	PageInfo             *PageInfo      `protobuf:"bytes,1,opt,name=pageInfo,proto3" json:"pageInfo,omitempty"`
	CrudResponse         *CrudResponse  `protobuf:"bytes,2,opt,name=crudResponse,proto3" json:"crudResponse,omitempty"`
	Logs                 []*AuditRecord `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AuditResponse) Reset()         { *m = AuditResponse{} }
func (m *AuditResponse) String() string { return proto.CompactTextString(m) }
func (*AuditResponse) ProtoMessage()    {}
func (*AuditResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5594839dd8e38a1b, []int{1}
}

func (m *AuditResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuditResponse.Unmarshal(m, b)
}
func (m *AuditResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuditResponse.Marshal(b, m, deterministic)
}
func (m *AuditResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditResponse.Merge(m, src)
}
func (m *AuditResponse) XXX_Size() int {
	return xxx_messageInfo_AuditResponse.Size(m)
}
func (m *AuditResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuditResponse proto.InternalMessageInfo

func (m *AuditResponse) GetPageInfo() *PageInfo {
	if m != nil {
		return m.PageInfo
	}
	return nil
}

func (m *AuditResponse) GetCrudResponse() *CrudResponse {
	if m != nil {
		return m.CrudResponse
	}
	return nil
}

func (m *AuditResponse) GetLogs() []*AuditRecord {
	if m != nil {
		return m.Logs
	}
	return nil
}

type ReadLogRequest struct {
	Log                  string   `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 int32    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadLogRequest) Reset()         { *m = ReadLogRequest{} }
func (m *ReadLogRequest) String() string { return proto.CompactTextString(m) }
func (*ReadLogRequest) ProtoMessage()    {}
func (*ReadLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5594839dd8e38a1b, []int{2}
}

func (m *ReadLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadLogRequest.Unmarshal(m, b)
}
func (m *ReadLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadLogRequest.Marshal(b, m, deterministic)
}
func (m *ReadLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadLogRequest.Merge(m, src)
}
func (m *ReadLogRequest) XXX_Size() int {
	return xxx_messageInfo_ReadLogRequest.Size(m)
}
func (m *ReadLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadLogRequest proto.InternalMessageInfo

func (m *ReadLogRequest) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

func (m *ReadLogRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ReadLogRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type AuditRecord struct {
	ID                   string              `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Timestamp            string              `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UserName             string              `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	Email                string              `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Role                 string              `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Action               string              `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`
	Status               string              `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Product              string              `protobuf:"bytes,8,opt,name=product,proto3" json:"product,omitempty"`
	Organization         string              `protobuf:"bytes,9,opt,name=organization,proto3" json:"organization,omitempty"`
	AuditDetails         *AuditRecordDetails `protobuf:"bytes,10,opt,name=auditDetails,proto3" json:"auditDetails,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AuditRecord) Reset()         { *m = AuditRecord{} }
func (m *AuditRecord) String() string { return proto.CompactTextString(m) }
func (*AuditRecord) ProtoMessage()    {}
func (*AuditRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_5594839dd8e38a1b, []int{3}
}

func (m *AuditRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuditRecord.Unmarshal(m, b)
}
func (m *AuditRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuditRecord.Marshal(b, m, deterministic)
}
func (m *AuditRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditRecord.Merge(m, src)
}
func (m *AuditRecord) XXX_Size() int {
	return xxx_messageInfo_AuditRecord.Size(m)
}
func (m *AuditRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditRecord.DiscardUnknown(m)
}

var xxx_messageInfo_AuditRecord proto.InternalMessageInfo

func (m *AuditRecord) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *AuditRecord) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *AuditRecord) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *AuditRecord) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuditRecord) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *AuditRecord) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *AuditRecord) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *AuditRecord) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *AuditRecord) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *AuditRecord) GetAuditDetails() *AuditRecordDetails {
	if m != nil {
		return m.AuditDetails
	}
	return nil
}

type AuditRecordDetails struct {
	Details              string   `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuditRecordDetails) Reset()         { *m = AuditRecordDetails{} }
func (m *AuditRecordDetails) String() string { return proto.CompactTextString(m) }
func (*AuditRecordDetails) ProtoMessage()    {}
func (*AuditRecordDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_5594839dd8e38a1b, []int{4}
}

func (m *AuditRecordDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuditRecordDetails.Unmarshal(m, b)
}
func (m *AuditRecordDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuditRecordDetails.Marshal(b, m, deterministic)
}
func (m *AuditRecordDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditRecordDetails.Merge(m, src)
}
func (m *AuditRecordDetails) XXX_Size() int {
	return xxx_messageInfo_AuditRecordDetails.Size(m)
}
func (m *AuditRecordDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditRecordDetails.DiscardUnknown(m)
}

var xxx_messageInfo_AuditRecordDetails proto.InternalMessageInfo

func (m *AuditRecordDetails) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func init() {
	proto.RegisterType((*SendLogRequest)(nil), "commonproto.SendLogRequest")
	proto.RegisterType((*AuditResponse)(nil), "commonproto.AuditResponse")
	proto.RegisterType((*ReadLogRequest)(nil), "commonproto.ReadLogRequest")
	proto.RegisterType((*AuditRecord)(nil), "commonproto.AuditRecord")
	proto.RegisterType((*AuditRecordDetails)(nil), "commonproto.AuditRecordDetails")
}

func init() { proto.RegisterFile("audit.proto", fileDescriptor_5594839dd8e38a1b) }

var fileDescriptor_5594839dd8e38a1b = []byte{
	// 443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x25, 0xed, 0xf6, 0x23, 0x93, 0x52, 0xad, 0x46, 0x80, 0x4c, 0x41, 0x62, 0x15, 0x71, 0xe8,
	0x01, 0x45, 0xa2, 0x9c, 0x39, 0xb0, 0x9b, 0x4b, 0xa5, 0x15, 0x5a, 0x19, 0x4e, 0xdc, 0xbc, 0x89,
	0x89, 0x2c, 0x25, 0x71, 0xb0, 0x1d, 0x09, 0xed, 0x2f, 0xe1, 0x5f, 0x70, 0xe1, 0x07, 0x22, 0x4f,
	0xdc, 0x25, 0xe1, 0xeb, 0xd4, 0x79, 0x6f, 0xde, 0x3c, 0x3f, 0xbb, 0x13, 0x48, 0x44, 0x5f, 0x2a,
	0x97, 0x75, 0x46, 0x3b, 0x8d, 0x49, 0xa1, 0x9b, 0x46, 0xb7, 0x04, 0x76, 0x50, 0x68, 0x23, 0x87,
	0x46, 0xfa, 0x12, 0xb6, 0x1f, 0x64, 0x5b, 0x5e, 0xeb, 0x8a, 0xcb, 0x2f, 0xbd, 0xb4, 0x0e, 0x11,
	0xce, 0x6a, 0x5d, 0x59, 0x16, 0x5d, 0x44, 0xfb, 0x0d, 0xa7, 0x3a, 0xfd, 0x1e, 0xc1, 0xc3, 0x77,
	0xde, 0x8e, 0x4b, 0xdb, 0xe9, 0xd6, 0x4a, 0x7c, 0x0d, 0xeb, 0x4e, 0x54, 0xf2, 0xd8, 0x7e, 0xd6,
	0xa4, 0x4c, 0x0e, 0x8f, 0xb3, 0xd1, 0x19, 0xd9, 0x4d, 0x68, 0xf2, 0x7b, 0x19, 0xbe, 0x85, 0x4d,
	0x61, 0xfa, 0xf2, 0x64, 0xc1, 0x66, 0x34, 0xf6, 0x74, 0x32, 0x76, 0x35, 0x12, 0xf0, 0x89, 0x1c,
	0x5f, 0x85, 0x5c, 0xf3, 0x8b, 0xf9, 0x3e, 0x39, 0xb0, 0xc9, 0x58, 0xc8, 0x56, 0x68, 0x53, 0x86,
	0xc4, 0xd7, 0xb0, 0xe5, 0x52, 0x8c, 0xef, 0x75, 0x0e, 0xf3, 0x5a, 0x57, 0x14, 0x36, 0xe6, 0xbe,
	0xc4, 0x47, 0xb0, 0xa8, 0x55, 0xa3, 0x1c, 0x25, 0x59, 0xf0, 0x01, 0xf8, 0xfb, 0xfb, 0xc8, 0x6c,
	0x4e, 0x24, 0xd5, 0xe9, 0x8f, 0x19, 0x24, 0xa3, 0x33, 0x70, 0x0b, 0xb3, 0x63, 0x1e, 0xac, 0x66,
	0xc7, 0x1c, 0x9f, 0x43, 0xec, 0x54, 0x23, 0xad, 0x13, 0x4d, 0x47, 0x6e, 0x31, 0xff, 0x45, 0xe0,
	0x0e, 0xd6, 0xbd, 0x95, 0xe6, 0xbd, 0x68, 0x06, 0xd7, 0x98, 0xdf, 0x63, 0x9f, 0x41, 0x36, 0x42,
	0xd5, 0xec, 0x8c, 0x1a, 0x03, 0xf0, 0x19, 0x8c, 0xae, 0x25, 0x5b, 0x10, 0x49, 0x35, 0x3e, 0x81,
	0xa5, 0x28, 0x9c, 0xd2, 0x2d, 0x5b, 0x12, 0x1b, 0x90, 0xe7, 0xad, 0x13, 0xae, 0xb7, 0x6c, 0x35,
	0xf0, 0x03, 0x42, 0x06, 0xab, 0xce, 0xe8, 0xb2, 0x2f, 0x1c, 0x5b, 0x53, 0xe3, 0x04, 0x31, 0x85,
	0x8d, 0x36, 0x95, 0x68, 0xd5, 0x9d, 0x20, 0xbf, 0x98, 0xda, 0x13, 0x0e, 0xaf, 0x60, 0x43, 0xfb,
	0x93, 0x4b, 0x27, 0x54, 0x6d, 0x19, 0xd0, 0x9f, 0xf5, 0xe2, 0x5f, 0xaf, 0x1e, 0x64, 0x7c, 0x32,
	0x94, 0x66, 0x80, 0x7f, 0x6a, 0x7c, 0xb0, 0x32, 0xb8, 0x0e, 0x2f, 0x78, 0x82, 0x87, 0x6f, 0x11,
	0x00, 0x0d, 0x7c, 0x34, 0xfe, 0x15, 0x72, 0x58, 0x85, 0xdd, 0xc4, 0x67, 0x93, 0x83, 0xa7, 0x1b,
	0xbb, 0xdb, 0xfd, 0x2d, 0xd5, 0xb0, 0x35, 0xe9, 0x03, 0xef, 0x12, 0x36, 0xe1, 0x37, 0x97, 0xe9,
	0x7e, 0xfc, 0xdf, 0xe5, 0x72, 0x0f, 0xe7, 0xaa, 0xcc, 0xee, 0xe4, 0xad, 0x11, 0x5f, 0x83, 0xf0,
	0x72, 0x41, 0xa2, 0x9b, 0xe8, 0xd3, 0xf8, 0xeb, 0xba, 0x5d, 0xd2, 0xcf, 0x9b, 0x9f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xeb, 0xc0, 0x7f, 0x05, 0x80, 0x03, 0x00, 0x00,
}
