// Code generated by protoc-gen-go. DO NOT EDIT.
// source: audit.proto

package commonproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendLogRequest struct {
	Logs                 []byte   `protobuf:"bytes,1,opt,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendLogRequest) Reset()         { *m = SendLogRequest{} }
func (m *SendLogRequest) String() string { return proto.CompactTextString(m) }
func (*SendLogRequest) ProtoMessage()    {}
func (*SendLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5594839dd8e38a1b, []int{0}
}

func (m *SendLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendLogRequest.Unmarshal(m, b)
}
func (m *SendLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendLogRequest.Marshal(b, m, deterministic)
}
func (m *SendLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendLogRequest.Merge(m, src)
}
func (m *SendLogRequest) XXX_Size() int {
	return xxx_messageInfo_SendLogRequest.Size(m)
}
func (m *SendLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendLogRequest proto.InternalMessageInfo

func (m *SendLogRequest) GetLogs() []byte {
	if m != nil {
		return m.Logs
	}
	return nil
}

type AuditResponse struct {
	CrudResponse         *CrudResponse `protobuf:"bytes,1,opt,name=crudResponse,proto3" json:"crudResponse,omitempty"`
	Logs                 [][]byte      `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AuditResponse) Reset()         { *m = AuditResponse{} }
func (m *AuditResponse) String() string { return proto.CompactTextString(m) }
func (*AuditResponse) ProtoMessage()    {}
func (*AuditResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5594839dd8e38a1b, []int{1}
}

func (m *AuditResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuditResponse.Unmarshal(m, b)
}
func (m *AuditResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuditResponse.Marshal(b, m, deterministic)
}
func (m *AuditResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditResponse.Merge(m, src)
}
func (m *AuditResponse) XXX_Size() int {
	return xxx_messageInfo_AuditResponse.Size(m)
}
func (m *AuditResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuditResponse proto.InternalMessageInfo

func (m *AuditResponse) GetCrudResponse() *CrudResponse {
	if m != nil {
		return m.CrudResponse
	}
	return nil
}

func (m *AuditResponse) GetLogs() [][]byte {
	if m != nil {
		return m.Logs
	}
	return nil
}

type ReadLogRequest struct {
	Log                  string   `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadLogRequest) Reset()         { *m = ReadLogRequest{} }
func (m *ReadLogRequest) String() string { return proto.CompactTextString(m) }
func (*ReadLogRequest) ProtoMessage()    {}
func (*ReadLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5594839dd8e38a1b, []int{2}
}

func (m *ReadLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadLogRequest.Unmarshal(m, b)
}
func (m *ReadLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadLogRequest.Marshal(b, m, deterministic)
}
func (m *ReadLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadLogRequest.Merge(m, src)
}
func (m *ReadLogRequest) XXX_Size() int {
	return xxx_messageInfo_ReadLogRequest.Size(m)
}
func (m *ReadLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadLogRequest proto.InternalMessageInfo

func (m *ReadLogRequest) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

func init() {
	proto.RegisterType((*SendLogRequest)(nil), "commonproto.SendLogRequest")
	proto.RegisterType((*AuditResponse)(nil), "commonproto.AuditResponse")
	proto.RegisterType((*ReadLogRequest)(nil), "commonproto.ReadLogRequest")
}

func init() { proto.RegisterFile("audit.proto", fileDescriptor_5594839dd8e38a1b) }

var fileDescriptor_5594839dd8e38a1b = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2c, 0x4d, 0xc9,
	0x2c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0x03,
	0x73, 0xa4, 0xb8, 0x92, 0xf3, 0x8b, 0x52, 0x21, 0x12, 0x4a, 0x2a, 0x5c, 0x7c, 0xc1, 0xa9, 0x79,
	0x29, 0x3e, 0xf9, 0xe9, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x42, 0x5c, 0x2c, 0x39,
	0xf9, 0xe9, 0xc5, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x60, 0xb6, 0x52, 0x12, 0x17, 0xaf,
	0x23, 0xc8, 0xb4, 0xa0, 0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x5b, 0x2e, 0x9e, 0xe4,
	0xa2, 0xd2, 0x14, 0x18, 0x1f, 0xac, 0x98, 0xdb, 0x48, 0x52, 0x0f, 0xc9, 0x1a, 0x3d, 0x67, 0x24,
	0x05, 0x41, 0x28, 0xca, 0xe1, 0x76, 0x30, 0x29, 0x30, 0xc3, 0xed, 0x50, 0xe2, 0xe2, 0x0b, 0x4a,
	0x4d, 0x44, 0x76, 0x89, 0x00, 0x17, 0x73, 0x4e, 0x7e, 0x3a, 0xd8, 0x6c, 0xce, 0x20, 0x10, 0xd3,
	0x68, 0x06, 0x23, 0x17, 0x17, 0xd8, 0x21, 0x21, 0x45, 0x89, 0x99, 0x39, 0x42, 0x2e, 0x5c, 0xec,
	0x50, 0xc7, 0x0b, 0x49, 0xa3, 0x58, 0x8d, 0xea, 0x25, 0x29, 0x29, 0x14, 0x49, 0x14, 0x9f, 0x28,
	0x31, 0x80, 0x4c, 0x81, 0x5a, 0x8c, 0x66, 0x0a, 0xaa, 0x73, 0xf0, 0x9b, 0xe2, 0xa4, 0xc1, 0x25,
	0x90, 0x99, 0xa2, 0x57, 0x95, 0x9a, 0x54, 0x94, 0x58, 0x01, 0x55, 0xe8, 0xc4, 0x0a, 0x56, 0x14,
	0xc0, 0x18, 0x85, 0x1c, 0xfc, 0x49, 0x6c, 0x60, 0xca, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xa7,
	0xcd, 0x40, 0xdd, 0xa1, 0x01, 0x00, 0x00,
}
