// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core.proto

package commonproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContentType int32

const (
	ContentType_KEY_VALUE_TEXT ContentType = 0
	ContentType_PLAIN_TEXT     ContentType = 1
	ContentType_HTML_TEXT      ContentType = 2
)

var ContentType_name = map[int32]string{
	0: "KEY_VALUE_TEXT",
	1: "PLAIN_TEXT",
	2: "HTML_TEXT",
}

var ContentType_value = map[string]int32{
	"KEY_VALUE_TEXT": 0,
	"PLAIN_TEXT":     1,
	"HTML_TEXT":      2,
}

func (x ContentType) String() string {
	return proto.EnumName(ContentType_name, int32(x))
}

func (ContentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{0}
}

type FieldName int32

const (
	FieldName_ID             FieldName = 0
	FieldName_NAME           FieldName = 1
	FieldName_PID            FieldName = 2
	FieldName_RESET_CODE     FieldName = 3
	FieldName_ORG_ID         FieldName = 4
	FieldName_OTP            FieldName = 5
	FieldName_OTP_CREATED_AT FieldName = 6
)

var FieldName_name = map[int32]string{
	0: "ID",
	1: "NAME",
	2: "PID",
	3: "RESET_CODE",
	4: "ORG_ID",
	5: "OTP",
	6: "OTP_CREATED_AT",
}

var FieldName_value = map[string]int32{
	"ID":             0,
	"NAME":           1,
	"PID":            2,
	"RESET_CODE":     3,
	"ORG_ID":         4,
	"OTP":            5,
	"OTP_CREATED_AT": 6,
}

func (x FieldName) String() string {
	return proto.EnumName(FieldName_name, int32(x))
}

func (FieldName) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{1}
}

type Comparison int32

const (
	Comparison_EQUAL        Comparison = 0
	Comparison_LESS         Comparison = 1
	Comparison_GERATER      Comparison = 2
	Comparison_LESSEQUAL    Comparison = 3
	Comparison_GREATEREQUAL Comparison = 4
	Comparison_LIKE         Comparison = 5
)

var Comparison_name = map[int32]string{
	0: "EQUAL",
	1: "LESS",
	2: "GERATER",
	3: "LESSEQUAL",
	4: "GREATEREQUAL",
	5: "LIKE",
}

var Comparison_value = map[string]int32{
	"EQUAL":        0,
	"LESS":         1,
	"GERATER":      2,
	"LESSEQUAL":    3,
	"GREATEREQUAL": 4,
	"LIKE":         5,
}

func (x Comparison) String() string {
	return proto.EnumName(Comparison_name, int32(x))
}

func (Comparison) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{2}
}

type CrudResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrudResponse) Reset()         { *m = CrudResponse{} }
func (m *CrudResponse) String() string { return proto.CompactTextString(m) }
func (*CrudResponse) ProtoMessage()    {}
func (*CrudResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{0}
}

func (m *CrudResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrudResponse.Unmarshal(m, b)
}
func (m *CrudResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrudResponse.Marshal(b, m, deterministic)
}
func (m *CrudResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrudResponse.Merge(m, src)
}
func (m *CrudResponse) XXX_Size() int {
	return xxx_messageInfo_CrudResponse.Size(m)
}
func (m *CrudResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CrudResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CrudResponse proto.InternalMessageInfo

func (m *CrudResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CrudResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PageInfo struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Total                int32    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageInfo) Reset()         { *m = PageInfo{} }
func (m *PageInfo) String() string { return proto.CompactTextString(m) }
func (*PageInfo) ProtoMessage()    {}
func (*PageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{1}
}

func (m *PageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageInfo.Unmarshal(m, b)
}
func (m *PageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageInfo.Marshal(b, m, deterministic)
}
func (m *PageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageInfo.Merge(m, src)
}
func (m *PageInfo) XXX_Size() int {
	return xxx_messageInfo_PageInfo.Size(m)
}
func (m *PageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PageInfo proto.InternalMessageInfo

func (m *PageInfo) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PageInfo) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *PageInfo) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterEnum("commonproto.ContentType", ContentType_name, ContentType_value)
	proto.RegisterEnum("commonproto.FieldName", FieldName_name, FieldName_value)
	proto.RegisterEnum("commonproto.Comparison", Comparison_name, Comparison_value)
	proto.RegisterType((*CrudResponse)(nil), "commonproto.CrudResponse")
	proto.RegisterType((*PageInfo)(nil), "commonproto.PageInfo")
}

func init() { proto.RegisterFile("core.proto", fileDescriptor_f7e43720d1edc0fe) }

var fileDescriptor_f7e43720d1edc0fe = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x4f, 0x8b, 0xdb, 0x30,
	0x10, 0xc5, 0xd7, 0x7f, 0xb3, 0x9e, 0x6c, 0x17, 0x31, 0x94, 0xe2, 0xe3, 0xb2, 0xa7, 0x10, 0x4a,
	0x2e, 0xfd, 0x02, 0x71, 0x6c, 0x35, 0x75, 0xe3, 0xc4, 0xae, 0xa2, 0x94, 0xa6, 0x17, 0xe3, 0x24,
	0x6a, 0x30, 0xc4, 0x96, 0xb1, 0x15, 0x68, 0xfb, 0xe9, 0x8b, 0xac, 0x16, 0x7a, 0x92, 0x7e, 0x8f,
	0xf7, 0x66, 0x06, 0x1e, 0xc0, 0x59, 0xf6, 0x62, 0xd1, 0xf5, 0x52, 0x49, 0x9c, 0x9e, 0x65, 0xd3,
	0xc8, 0x76, 0x84, 0xd7, 0x25, 0x3c, 0xc5, 0xfd, 0xfd, 0xc2, 0xc4, 0xd0, 0xc9, 0x76, 0x10, 0xf8,
	0x0e, 0xfc, 0x41, 0x55, 0xea, 0x3e, 0x84, 0xd6, 0x8b, 0x35, 0xf3, 0xd8, 0x5f, 0xc2, 0x10, 0x26,
	0x8d, 0x18, 0x86, 0xea, 0x2a, 0x42, 0xfb, 0xc5, 0x9a, 0x05, 0xec, 0x1f, 0xbe, 0x7e, 0x86, 0xc7,
	0xa2, 0xba, 0x8a, 0xb4, 0xfd, 0x21, 0x11, 0xc1, 0xed, 0xb4, 0xc5, 0x64, 0xc7, 0x3f, 0xbe, 0x05,
	0xef, 0x56, 0x37, 0xb5, 0x1a, 0x73, 0x1e, 0x33, 0xa0, 0x55, 0x25, 0x55, 0x75, 0x0b, 0x1d, 0xa3,
	0x8e, 0x30, 0x5f, 0xc2, 0x34, 0x96, 0xad, 0x12, 0xad, 0xe2, 0xbf, 0x3a, 0x81, 0x08, 0xcf, 0x1b,
	0x7a, 0x2c, 0xbf, 0x46, 0xd9, 0x81, 0x96, 0x9c, 0x7e, 0xe3, 0xe4, 0x01, 0x9f, 0x01, 0x8a, 0x2c,
	0x4a, 0x77, 0x86, 0x2d, 0x7c, 0x03, 0xc1, 0x27, 0xbe, 0xcd, 0x0c, 0xda, 0xf3, 0x12, 0x82, 0x8f,
	0xb5, 0xb8, 0x5d, 0x76, 0x55, 0x23, 0xd0, 0x07, 0x3b, 0x4d, 0xc8, 0x03, 0x3e, 0x82, 0xbb, 0x8b,
	0xb6, 0x94, 0x58, 0x38, 0x01, 0xa7, 0x48, 0x13, 0x62, 0xeb, 0x31, 0x8c, 0xee, 0x29, 0x2f, 0xe3,
	0x3c, 0xa1, 0xc4, 0x41, 0x00, 0x3f, 0x67, 0xeb, 0x32, 0x4d, 0x88, 0xab, 0x4d, 0x39, 0x2f, 0x88,
	0xa7, 0xf7, 0xe7, 0xbc, 0x28, 0x63, 0x46, 0x23, 0x4e, 0x93, 0x32, 0xe2, 0xc4, 0x9f, 0x1f, 0x01,
	0x62, 0xd9, 0x74, 0x55, 0x5f, 0x0f, 0xb2, 0xc5, 0x00, 0x3c, 0xfa, 0xe5, 0x10, 0x65, 0x66, 0x49,
	0x46, 0xf7, 0x7b, 0x62, 0xe1, 0x14, 0x26, 0x6b, 0xca, 0x22, 0x4e, 0x19, 0xb1, 0xf5, 0x7d, 0x5a,
	0x36, 0x2e, 0x07, 0x09, 0x3c, 0xad, 0xc7, 0x71, 0xcc, 0x28, 0xee, 0x98, 0x4b, 0x37, 0x94, 0x78,
	0xab, 0xf7, 0x40, 0xea, 0xcb, 0xe2, 0xb7, 0x38, 0xf5, 0xd5, 0xcf, 0x85, 0x29, 0x69, 0x15, 0xc4,
	0xb2, 0x17, 0x85, 0xae, 0xaa, 0xb0, 0xbe, 0xff, 0xdf, 0xdc, 0xc9, 0x1f, 0x9f, 0x0f, 0x7f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xd8, 0x5e, 0x0d, 0xc9, 0xdb, 0x01, 0x00, 0x00,
}
