// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notification.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EditNotificationPermissionParam struct {
	ID                   string                                    `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	NotificationType     string                                    `protobuf:"bytes,2,opt,name=notificationType,proto3" json:"notificationType,omitempty"`
	ServiceType          []*NotificationServiceTypePermissionParam `protobuf:"bytes,3,rep,name=serviceType,proto3" json:"serviceType,omitempty"`
	ProductID            string                                    `protobuf:"bytes,4,opt,name=productID,proto3" json:"productID,omitempty"`
	Recipients           *NotificationPermissionRecipientsParam    `protobuf:"bytes,5,opt,name=recipients,proto3" json:"recipients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *EditNotificationPermissionParam) Reset()         { *m = EditNotificationPermissionParam{} }
func (m *EditNotificationPermissionParam) String() string { return proto.CompactTextString(m) }
func (*EditNotificationPermissionParam) ProtoMessage()    {}
func (*EditNotificationPermissionParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{0}
}

func (m *EditNotificationPermissionParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditNotificationPermissionParam.Unmarshal(m, b)
}
func (m *EditNotificationPermissionParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditNotificationPermissionParam.Marshal(b, m, deterministic)
}
func (m *EditNotificationPermissionParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditNotificationPermissionParam.Merge(m, src)
}
func (m *EditNotificationPermissionParam) XXX_Size() int {
	return xxx_messageInfo_EditNotificationPermissionParam.Size(m)
}
func (m *EditNotificationPermissionParam) XXX_DiscardUnknown() {
	xxx_messageInfo_EditNotificationPermissionParam.DiscardUnknown(m)
}

var xxx_messageInfo_EditNotificationPermissionParam proto.InternalMessageInfo

func (m *EditNotificationPermissionParam) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *EditNotificationPermissionParam) GetNotificationType() string {
	if m != nil {
		return m.NotificationType
	}
	return ""
}

func (m *EditNotificationPermissionParam) GetServiceType() []*NotificationServiceTypePermissionParam {
	if m != nil {
		return m.ServiceType
	}
	return nil
}

func (m *EditNotificationPermissionParam) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *EditNotificationPermissionParam) GetRecipients() *NotificationPermissionRecipientsParam {
	if m != nil {
		return m.Recipients
	}
	return nil
}

type NotificationServiceTypePermissionParam struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	IsMandatory          bool     `protobuf:"varint,2,opt,name=isMandatory,proto3" json:"isMandatory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationServiceTypePermissionParam) Reset() {
	*m = NotificationServiceTypePermissionParam{}
}
func (m *NotificationServiceTypePermissionParam) String() string { return proto.CompactTextString(m) }
func (*NotificationServiceTypePermissionParam) ProtoMessage()    {}
func (*NotificationServiceTypePermissionParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{1}
}

func (m *NotificationServiceTypePermissionParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationServiceTypePermissionParam.Unmarshal(m, b)
}
func (m *NotificationServiceTypePermissionParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationServiceTypePermissionParam.Marshal(b, m, deterministic)
}
func (m *NotificationServiceTypePermissionParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationServiceTypePermissionParam.Merge(m, src)
}
func (m *NotificationServiceTypePermissionParam) XXX_Size() int {
	return xxx_messageInfo_NotificationServiceTypePermissionParam.Size(m)
}
func (m *NotificationServiceTypePermissionParam) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationServiceTypePermissionParam.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationServiceTypePermissionParam proto.InternalMessageInfo

func (m *NotificationServiceTypePermissionParam) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *NotificationServiceTypePermissionParam) GetIsMandatory() bool {
	if m != nil {
		return m.IsMandatory
	}
	return false
}

type NotificationPermissionRecipientsParam struct {
	Users                []string `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Group                string   `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationPermissionRecipientsParam) Reset()         { *m = NotificationPermissionRecipientsParam{} }
func (m *NotificationPermissionRecipientsParam) String() string { return proto.CompactTextString(m) }
func (*NotificationPermissionRecipientsParam) ProtoMessage()    {}
func (*NotificationPermissionRecipientsParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{2}
}

func (m *NotificationPermissionRecipientsParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationPermissionRecipientsParam.Unmarshal(m, b)
}
func (m *NotificationPermissionRecipientsParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationPermissionRecipientsParam.Marshal(b, m, deterministic)
}
func (m *NotificationPermissionRecipientsParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationPermissionRecipientsParam.Merge(m, src)
}
func (m *NotificationPermissionRecipientsParam) XXX_Size() int {
	return xxx_messageInfo_NotificationPermissionRecipientsParam.Size(m)
}
func (m *NotificationPermissionRecipientsParam) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationPermissionRecipientsParam.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationPermissionRecipientsParam proto.InternalMessageInfo

func (m *NotificationPermissionRecipientsParam) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *NotificationPermissionRecipientsParam) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

type NotificationRequest struct {
	SendNotificationRequest      *SendNotificationRequest         `protobuf:"bytes,1,opt,name=sendNotificationRequest,proto3" json:"sendNotificationRequest,omitempty"`
	NotificationTemplate         *NotificationTemplate            `protobuf:"bytes,2,opt,name=notificationTemplate,proto3" json:"notificationTemplate,omitempty"`
	NotificationList             *NotificationList                `protobuf:"bytes,3,opt,name=notificationList,proto3" json:"notificationList,omitempty"`
	NotificationRetry            *NotificationRetry               `protobuf:"bytes,4,opt,name=notificationRetry,proto3" json:"notificationRetry,omitempty"`
	NotificationGroupParam       *NotificationGroupParam          `protobuf:"bytes,5,opt,name=notificationGroupParam,proto3" json:"notificationGroupParam,omitempty"`
	NotificationGroupMemberParam *NotificationGroupMemberParam    `protobuf:"bytes,6,opt,name=notificationGroupMemberParam,proto3" json:"notificationGroupMemberParam,omitempty"`
	NotificationPermission       *EditNotificationPermissionParam `protobuf:"bytes,7,opt,name=notificationPermission,proto3" json:"notificationPermission,omitempty"`
	NotificationPermissionList   *NotificationPermissionListParam `protobuf:"bytes,8,opt,name=notificationPermissionList,proto3" json:"notificationPermissionList,omitempty"`
	NotificationLogListParam     *NotificationLogListParam        `protobuf:"bytes,9,opt,name=notificationLogListParam,proto3" json:"notificationLogListParam,omitempty"`
	NotificationGroupListParam   *NotificationGroupListParam      `protobuf:"bytes,10,opt,name=notificationGroupListParam,proto3" json:"notificationGroupListParam,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}                         `json:"-"`
	XXX_unrecognized             []byte                           `json:"-"`
	XXX_sizecache                int32                            `json:"-"`
}

func (m *NotificationRequest) Reset()         { *m = NotificationRequest{} }
func (m *NotificationRequest) String() string { return proto.CompactTextString(m) }
func (*NotificationRequest) ProtoMessage()    {}
func (*NotificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{3}
}

func (m *NotificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationRequest.Unmarshal(m, b)
}
func (m *NotificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationRequest.Marshal(b, m, deterministic)
}
func (m *NotificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationRequest.Merge(m, src)
}
func (m *NotificationRequest) XXX_Size() int {
	return xxx_messageInfo_NotificationRequest.Size(m)
}
func (m *NotificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationRequest proto.InternalMessageInfo

func (m *NotificationRequest) GetSendNotificationRequest() *SendNotificationRequest {
	if m != nil {
		return m.SendNotificationRequest
	}
	return nil
}

func (m *NotificationRequest) GetNotificationTemplate() *NotificationTemplate {
	if m != nil {
		return m.NotificationTemplate
	}
	return nil
}

func (m *NotificationRequest) GetNotificationList() *NotificationList {
	if m != nil {
		return m.NotificationList
	}
	return nil
}

func (m *NotificationRequest) GetNotificationRetry() *NotificationRetry {
	if m != nil {
		return m.NotificationRetry
	}
	return nil
}

func (m *NotificationRequest) GetNotificationGroupParam() *NotificationGroupParam {
	if m != nil {
		return m.NotificationGroupParam
	}
	return nil
}

func (m *NotificationRequest) GetNotificationGroupMemberParam() *NotificationGroupMemberParam {
	if m != nil {
		return m.NotificationGroupMemberParam
	}
	return nil
}

func (m *NotificationRequest) GetNotificationPermission() *EditNotificationPermissionParam {
	if m != nil {
		return m.NotificationPermission
	}
	return nil
}

func (m *NotificationRequest) GetNotificationPermissionList() *NotificationPermissionListParam {
	if m != nil {
		return m.NotificationPermissionList
	}
	return nil
}

func (m *NotificationRequest) GetNotificationLogListParam() *NotificationLogListParam {
	if m != nil {
		return m.NotificationLogListParam
	}
	return nil
}

func (m *NotificationRequest) GetNotificationGroupListParam() *NotificationGroupListParam {
	if m != nil {
		return m.NotificationGroupListParam
	}
	return nil
}

type NotificationGroupMemberParam struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupID              string   `protobuf:"bytes,2,opt,name=groupID,proto3" json:"groupID,omitempty"`
	UserID               []string `protobuf:"bytes,3,rep,name=userID,proto3" json:"userID,omitempty"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy            string   `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy            string   `protobuf:"bytes,7,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationGroupMemberParam) Reset()         { *m = NotificationGroupMemberParam{} }
func (m *NotificationGroupMemberParam) String() string { return proto.CompactTextString(m) }
func (*NotificationGroupMemberParam) ProtoMessage()    {}
func (*NotificationGroupMemberParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{4}
}

func (m *NotificationGroupMemberParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationGroupMemberParam.Unmarshal(m, b)
}
func (m *NotificationGroupMemberParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationGroupMemberParam.Marshal(b, m, deterministic)
}
func (m *NotificationGroupMemberParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationGroupMemberParam.Merge(m, src)
}
func (m *NotificationGroupMemberParam) XXX_Size() int {
	return xxx_messageInfo_NotificationGroupMemberParam.Size(m)
}
func (m *NotificationGroupMemberParam) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationGroupMemberParam.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationGroupMemberParam proto.InternalMessageInfo

func (m *NotificationGroupMemberParam) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NotificationGroupMemberParam) GetGroupID() string {
	if m != nil {
		return m.GroupID
	}
	return ""
}

func (m *NotificationGroupMemberParam) GetUserID() []string {
	if m != nil {
		return m.UserID
	}
	return nil
}

func (m *NotificationGroupMemberParam) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *NotificationGroupMemberParam) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *NotificationGroupMemberParam) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *NotificationGroupMemberParam) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

type NotificationGroupListParam struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	GroupID              string   `protobuf:"bytes,3,opt,name=groupID,proto3" json:"groupID,omitempty"`
	GroupName            string   `protobuf:"bytes,4,opt,name=groupName,proto3" json:"groupName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationGroupListParam) Reset()         { *m = NotificationGroupListParam{} }
func (m *NotificationGroupListParam) String() string { return proto.CompactTextString(m) }
func (*NotificationGroupListParam) ProtoMessage()    {}
func (*NotificationGroupListParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{5}
}

func (m *NotificationGroupListParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationGroupListParam.Unmarshal(m, b)
}
func (m *NotificationGroupListParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationGroupListParam.Marshal(b, m, deterministic)
}
func (m *NotificationGroupListParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationGroupListParam.Merge(m, src)
}
func (m *NotificationGroupListParam) XXX_Size() int {
	return xxx_messageInfo_NotificationGroupListParam.Size(m)
}
func (m *NotificationGroupListParam) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationGroupListParam.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationGroupListParam proto.InternalMessageInfo

func (m *NotificationGroupListParam) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *NotificationGroupListParam) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *NotificationGroupListParam) GetGroupID() string {
	if m != nil {
		return m.GroupID
	}
	return ""
}

func (m *NotificationGroupListParam) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

type NotificationPermissionListParam struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationPermissionListParam) Reset()         { *m = NotificationPermissionListParam{} }
func (m *NotificationPermissionListParam) String() string { return proto.CompactTextString(m) }
func (*NotificationPermissionListParam) ProtoMessage()    {}
func (*NotificationPermissionListParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{6}
}

func (m *NotificationPermissionListParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationPermissionListParam.Unmarshal(m, b)
}
func (m *NotificationPermissionListParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationPermissionListParam.Marshal(b, m, deterministic)
}
func (m *NotificationPermissionListParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationPermissionListParam.Merge(m, src)
}
func (m *NotificationPermissionListParam) XXX_Size() int {
	return xxx_messageInfo_NotificationPermissionListParam.Size(m)
}
func (m *NotificationPermissionListParam) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationPermissionListParam.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationPermissionListParam proto.InternalMessageInfo

func (m *NotificationPermissionListParam) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type NotificationLogListParam struct {
	Product              string            `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Channel              string            `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Content              string            `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Daterange            *LogListDateRange `protobuf:"bytes,4,opt,name=daterange,proto3" json:"daterange,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NotificationLogListParam) Reset()         { *m = NotificationLogListParam{} }
func (m *NotificationLogListParam) String() string { return proto.CompactTextString(m) }
func (*NotificationLogListParam) ProtoMessage()    {}
func (*NotificationLogListParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{7}
}

func (m *NotificationLogListParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationLogListParam.Unmarshal(m, b)
}
func (m *NotificationLogListParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationLogListParam.Marshal(b, m, deterministic)
}
func (m *NotificationLogListParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationLogListParam.Merge(m, src)
}
func (m *NotificationLogListParam) XXX_Size() int {
	return xxx_messageInfo_NotificationLogListParam.Size(m)
}
func (m *NotificationLogListParam) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationLogListParam.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationLogListParam proto.InternalMessageInfo

func (m *NotificationLogListParam) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *NotificationLogListParam) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *NotificationLogListParam) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *NotificationLogListParam) GetDaterange() *LogListDateRange {
	if m != nil {
		return m.Daterange
	}
	return nil
}

type LogListDateRange struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogListDateRange) Reset()         { *m = LogListDateRange{} }
func (m *LogListDateRange) String() string { return proto.CompactTextString(m) }
func (*LogListDateRange) ProtoMessage()    {}
func (*LogListDateRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{8}
}

func (m *LogListDateRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogListDateRange.Unmarshal(m, b)
}
func (m *LogListDateRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogListDateRange.Marshal(b, m, deterministic)
}
func (m *LogListDateRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogListDateRange.Merge(m, src)
}
func (m *LogListDateRange) XXX_Size() int {
	return xxx_messageInfo_LogListDateRange.Size(m)
}
func (m *LogListDateRange) XXX_DiscardUnknown() {
	xxx_messageInfo_LogListDateRange.DiscardUnknown(m)
}

var xxx_messageInfo_LogListDateRange proto.InternalMessageInfo

func (m *LogListDateRange) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *LogListDateRange) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type NotificationContentRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationContentRequest) Reset()         { *m = NotificationContentRequest{} }
func (m *NotificationContentRequest) String() string { return proto.CompactTextString(m) }
func (*NotificationContentRequest) ProtoMessage()    {}
func (*NotificationContentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{9}
}

func (m *NotificationContentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationContentRequest.Unmarshal(m, b)
}
func (m *NotificationContentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationContentRequest.Marshal(b, m, deterministic)
}
func (m *NotificationContentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationContentRequest.Merge(m, src)
}
func (m *NotificationContentRequest) XXX_Size() int {
	return xxx_messageInfo_NotificationContentRequest.Size(m)
}
func (m *NotificationContentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationContentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationContentRequest proto.InternalMessageInfo

func (m *NotificationContentRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *NotificationContentRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SendNotificationRequest struct {
	ProductID            string                        `protobuf:"bytes,1,opt,name=productID,proto3" json:"productID,omitempty"`
	ServiceType          string                        `protobuf:"bytes,2,opt,name=serviceType,proto3" json:"serviceType,omitempty"`
	NotificationType     string                        `protobuf:"bytes,3,opt,name=notificationType,proto3" json:"notificationType,omitempty"`
	To                   []string                      `protobuf:"bytes,4,rep,name=to,proto3" json:"to,omitempty"`
	Cc                   []string                      `protobuf:"bytes,5,rep,name=cc,proto3" json:"cc,omitempty"`
	KeyValContent        []*NotificationContentRequest `protobuf:"bytes,6,rep,name=keyValContent,proto3" json:"keyValContent,omitempty"`
	Content              string                        `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	From                 string                        `protobuf:"bytes,8,opt,name=from,proto3" json:"from,omitempty"`
	ContentType          ContentType                   `protobuf:"varint,9,opt,name=contentType,proto3,enum=proto.ContentType" json:"contentType,omitempty"`
	TrackerID            string                        `protobuf:"bytes,10,opt,name=trackerID,proto3" json:"trackerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *SendNotificationRequest) Reset()         { *m = SendNotificationRequest{} }
func (m *SendNotificationRequest) String() string { return proto.CompactTextString(m) }
func (*SendNotificationRequest) ProtoMessage()    {}
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{10}
}

func (m *SendNotificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendNotificationRequest.Unmarshal(m, b)
}
func (m *SendNotificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendNotificationRequest.Marshal(b, m, deterministic)
}
func (m *SendNotificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendNotificationRequest.Merge(m, src)
}
func (m *SendNotificationRequest) XXX_Size() int {
	return xxx_messageInfo_SendNotificationRequest.Size(m)
}
func (m *SendNotificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendNotificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendNotificationRequest proto.InternalMessageInfo

func (m *SendNotificationRequest) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *SendNotificationRequest) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *SendNotificationRequest) GetNotificationType() string {
	if m != nil {
		return m.NotificationType
	}
	return ""
}

func (m *SendNotificationRequest) GetTo() []string {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *SendNotificationRequest) GetCc() []string {
	if m != nil {
		return m.Cc
	}
	return nil
}

func (m *SendNotificationRequest) GetKeyValContent() []*NotificationContentRequest {
	if m != nil {
		return m.KeyValContent
	}
	return nil
}

func (m *SendNotificationRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *SendNotificationRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *SendNotificationRequest) GetContentType() ContentType {
	if m != nil {
		return m.ContentType
	}
	return ContentType_KEY_VALUE_TEXT
}

func (m *SendNotificationRequest) GetTrackerID() string {
	if m != nil {
		return m.TrackerID
	}
	return ""
}

type NotificationResponse struct {
	Response             *CrudResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NotificationResponse) Reset()         { *m = NotificationResponse{} }
func (m *NotificationResponse) String() string { return proto.CompactTextString(m) }
func (*NotificationResponse) ProtoMessage()    {}
func (*NotificationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{11}
}

func (m *NotificationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationResponse.Unmarshal(m, b)
}
func (m *NotificationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationResponse.Marshal(b, m, deterministic)
}
func (m *NotificationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationResponse.Merge(m, src)
}
func (m *NotificationResponse) XXX_Size() int {
	return xxx_messageInfo_NotificationResponse.Size(m)
}
func (m *NotificationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationResponse proto.InternalMessageInfo

func (m *NotificationResponse) GetResponse() *CrudResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

type NotificationListResponse struct {
	PageInfo                    *PageInfo                      `protobuf:"bytes,1,opt,name=pageInfo,proto3" json:"pageInfo,omitempty"`
	PermissionList              []*NotificationPermissionList  `protobuf:"bytes,2,rep,name=permissionList,proto3" json:"permissionList,omitempty"`
	LogList                     []*NotificationLog             `protobuf:"bytes,3,rep,name=logList,proto3" json:"logList,omitempty"`
	NotificationGroupList       []*NotificationGroupList       `protobuf:"bytes,4,rep,name=notificationGroupList,proto3" json:"notificationGroupList,omitempty"`
	NotificationGroupMemberList []*NotificationGroupMemberList `protobuf:"bytes,5,rep,name=notificationGroupMemberList,proto3" json:"notificationGroupMemberList,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}                       `json:"-"`
	XXX_unrecognized            []byte                         `json:"-"`
	XXX_sizecache               int32                          `json:"-"`
}

func (m *NotificationListResponse) Reset()         { *m = NotificationListResponse{} }
func (m *NotificationListResponse) String() string { return proto.CompactTextString(m) }
func (*NotificationListResponse) ProtoMessage()    {}
func (*NotificationListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{12}
}

func (m *NotificationListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationListResponse.Unmarshal(m, b)
}
func (m *NotificationListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationListResponse.Marshal(b, m, deterministic)
}
func (m *NotificationListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationListResponse.Merge(m, src)
}
func (m *NotificationListResponse) XXX_Size() int {
	return xxx_messageInfo_NotificationListResponse.Size(m)
}
func (m *NotificationListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationListResponse proto.InternalMessageInfo

func (m *NotificationListResponse) GetPageInfo() *PageInfo {
	if m != nil {
		return m.PageInfo
	}
	return nil
}

func (m *NotificationListResponse) GetPermissionList() []*NotificationPermissionList {
	if m != nil {
		return m.PermissionList
	}
	return nil
}

func (m *NotificationListResponse) GetLogList() []*NotificationLog {
	if m != nil {
		return m.LogList
	}
	return nil
}

func (m *NotificationListResponse) GetNotificationGroupList() []*NotificationGroupList {
	if m != nil {
		return m.NotificationGroupList
	}
	return nil
}

func (m *NotificationListResponse) GetNotificationGroupMemberList() []*NotificationGroupMemberList {
	if m != nil {
		return m.NotificationGroupMemberList
	}
	return nil
}

type NotificationGroupList struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationGroupList) Reset()         { *m = NotificationGroupList{} }
func (m *NotificationGroupList) String() string { return proto.CompactTextString(m) }
func (*NotificationGroupList) ProtoMessage()    {}
func (*NotificationGroupList) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{13}
}

func (m *NotificationGroupList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationGroupList.Unmarshal(m, b)
}
func (m *NotificationGroupList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationGroupList.Marshal(b, m, deterministic)
}
func (m *NotificationGroupList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationGroupList.Merge(m, src)
}
func (m *NotificationGroupList) XXX_Size() int {
	return xxx_messageInfo_NotificationGroupList.Size(m)
}
func (m *NotificationGroupList) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationGroupList.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationGroupList proto.InternalMessageInfo

func (m *NotificationGroupList) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *NotificationGroupList) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NotificationGroupList) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type NotificationGroupMemberList struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	GroupID              string   `protobuf:"bytes,2,opt,name=groupID,proto3" json:"groupID,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationGroupMemberList) Reset()         { *m = NotificationGroupMemberList{} }
func (m *NotificationGroupMemberList) String() string { return proto.CompactTextString(m) }
func (*NotificationGroupMemberList) ProtoMessage()    {}
func (*NotificationGroupMemberList) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{14}
}

func (m *NotificationGroupMemberList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationGroupMemberList.Unmarshal(m, b)
}
func (m *NotificationGroupMemberList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationGroupMemberList.Marshal(b, m, deterministic)
}
func (m *NotificationGroupMemberList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationGroupMemberList.Merge(m, src)
}
func (m *NotificationGroupMemberList) XXX_Size() int {
	return xxx_messageInfo_NotificationGroupMemberList.Size(m)
}
func (m *NotificationGroupMemberList) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationGroupMemberList.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationGroupMemberList proto.InternalMessageInfo

func (m *NotificationGroupMemberList) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *NotificationGroupMemberList) GetGroupID() string {
	if m != nil {
		return m.GroupID
	}
	return ""
}

func (m *NotificationGroupMemberList) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NotificationGroupMemberList) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type NotificationPermissionList struct {
	ID                   string                               `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	NotificationType     string                               `protobuf:"bytes,2,opt,name=notificationType,proto3" json:"notificationType,omitempty"`
	ServiceType          []*NotificationServiceTypePermission `protobuf:"bytes,3,rep,name=serviceType,proto3" json:"serviceType,omitempty"`
	Product              *NotificationProductPermission       `protobuf:"bytes,4,opt,name=product,proto3" json:"product,omitempty"`
	Recipients           *NotificationPermissionRecipients    `protobuf:"bytes,5,opt,name=recipients,proto3" json:"recipients,omitempty"`
	OrgID                string                               `protobuf:"bytes,6,opt,name=orgID,proto3" json:"orgID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *NotificationPermissionList) Reset()         { *m = NotificationPermissionList{} }
func (m *NotificationPermissionList) String() string { return proto.CompactTextString(m) }
func (*NotificationPermissionList) ProtoMessage()    {}
func (*NotificationPermissionList) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{15}
}

func (m *NotificationPermissionList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationPermissionList.Unmarshal(m, b)
}
func (m *NotificationPermissionList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationPermissionList.Marshal(b, m, deterministic)
}
func (m *NotificationPermissionList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationPermissionList.Merge(m, src)
}
func (m *NotificationPermissionList) XXX_Size() int {
	return xxx_messageInfo_NotificationPermissionList.Size(m)
}
func (m *NotificationPermissionList) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationPermissionList.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationPermissionList proto.InternalMessageInfo

func (m *NotificationPermissionList) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *NotificationPermissionList) GetNotificationType() string {
	if m != nil {
		return m.NotificationType
	}
	return ""
}

func (m *NotificationPermissionList) GetServiceType() []*NotificationServiceTypePermission {
	if m != nil {
		return m.ServiceType
	}
	return nil
}

func (m *NotificationPermissionList) GetProduct() *NotificationProductPermission {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *NotificationPermissionList) GetRecipients() *NotificationPermissionRecipients {
	if m != nil {
		return m.Recipients
	}
	return nil
}

func (m *NotificationPermissionList) GetOrgID() string {
	if m != nil {
		return m.OrgID
	}
	return ""
}

type NotificationServiceTypePermission struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	IsMandatory          bool     `protobuf:"varint,2,opt,name=isMandatory,proto3" json:"isMandatory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationServiceTypePermission) Reset()         { *m = NotificationServiceTypePermission{} }
func (m *NotificationServiceTypePermission) String() string { return proto.CompactTextString(m) }
func (*NotificationServiceTypePermission) ProtoMessage()    {}
func (*NotificationServiceTypePermission) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{16}
}

func (m *NotificationServiceTypePermission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationServiceTypePermission.Unmarshal(m, b)
}
func (m *NotificationServiceTypePermission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationServiceTypePermission.Marshal(b, m, deterministic)
}
func (m *NotificationServiceTypePermission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationServiceTypePermission.Merge(m, src)
}
func (m *NotificationServiceTypePermission) XXX_Size() int {
	return xxx_messageInfo_NotificationServiceTypePermission.Size(m)
}
func (m *NotificationServiceTypePermission) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationServiceTypePermission.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationServiceTypePermission proto.InternalMessageInfo

func (m *NotificationServiceTypePermission) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *NotificationServiceTypePermission) GetIsMandatory() bool {
	if m != nil {
		return m.IsMandatory
	}
	return false
}

type NotificationProductPermission struct {
	ProductID            string   `protobuf:"bytes,1,opt,name=productID,proto3" json:"productID,omitempty"`
	ProductName          string   `protobuf:"bytes,2,opt,name=productName,proto3" json:"productName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationProductPermission) Reset()         { *m = NotificationProductPermission{} }
func (m *NotificationProductPermission) String() string { return proto.CompactTextString(m) }
func (*NotificationProductPermission) ProtoMessage()    {}
func (*NotificationProductPermission) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{17}
}

func (m *NotificationProductPermission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationProductPermission.Unmarshal(m, b)
}
func (m *NotificationProductPermission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationProductPermission.Marshal(b, m, deterministic)
}
func (m *NotificationProductPermission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationProductPermission.Merge(m, src)
}
func (m *NotificationProductPermission) XXX_Size() int {
	return xxx_messageInfo_NotificationProductPermission.Size(m)
}
func (m *NotificationProductPermission) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationProductPermission.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationProductPermission proto.InternalMessageInfo

func (m *NotificationProductPermission) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *NotificationProductPermission) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

type NotificationPermissionRecipients struct {
	Users                []*NotificationPermissionRecipientUsers `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Group                *NotificationPermissionRecipientUsers   `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *NotificationPermissionRecipients) Reset()         { *m = NotificationPermissionRecipients{} }
func (m *NotificationPermissionRecipients) String() string { return proto.CompactTextString(m) }
func (*NotificationPermissionRecipients) ProtoMessage()    {}
func (*NotificationPermissionRecipients) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{18}
}

func (m *NotificationPermissionRecipients) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationPermissionRecipients.Unmarshal(m, b)
}
func (m *NotificationPermissionRecipients) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationPermissionRecipients.Marshal(b, m, deterministic)
}
func (m *NotificationPermissionRecipients) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationPermissionRecipients.Merge(m, src)
}
func (m *NotificationPermissionRecipients) XXX_Size() int {
	return xxx_messageInfo_NotificationPermissionRecipients.Size(m)
}
func (m *NotificationPermissionRecipients) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationPermissionRecipients.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationPermissionRecipients proto.InternalMessageInfo

func (m *NotificationPermissionRecipients) GetUsers() []*NotificationPermissionRecipientUsers {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *NotificationPermissionRecipients) GetGroup() *NotificationPermissionRecipientUsers {
	if m != nil {
		return m.Group
	}
	return nil
}

type NotificationPermissionRecipientUsers struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationPermissionRecipientUsers) Reset()         { *m = NotificationPermissionRecipientUsers{} }
func (m *NotificationPermissionRecipientUsers) String() string { return proto.CompactTextString(m) }
func (*NotificationPermissionRecipientUsers) ProtoMessage()    {}
func (*NotificationPermissionRecipientUsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{19}
}

func (m *NotificationPermissionRecipientUsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationPermissionRecipientUsers.Unmarshal(m, b)
}
func (m *NotificationPermissionRecipientUsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationPermissionRecipientUsers.Marshal(b, m, deterministic)
}
func (m *NotificationPermissionRecipientUsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationPermissionRecipientUsers.Merge(m, src)
}
func (m *NotificationPermissionRecipientUsers) XXX_Size() int {
	return xxx_messageInfo_NotificationPermissionRecipientUsers.Size(m)
}
func (m *NotificationPermissionRecipientUsers) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationPermissionRecipientUsers.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationPermissionRecipientUsers proto.InternalMessageInfo

func (m *NotificationPermissionRecipientUsers) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *NotificationPermissionRecipientUsers) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type NotificationTemplate struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceType          string   `protobuf:"bytes,2,opt,name=serviceType,proto3" json:"serviceType,omitempty"`
	NotificationType     string   `protobuf:"bytes,3,opt,name=notificationType,proto3" json:"notificationType,omitempty"`
	Template             string   `protobuf:"bytes,4,opt,name=template,proto3" json:"template,omitempty"`
	Subject              string   `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy            string   `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy            string   `protobuf:"bytes,9,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationTemplate) Reset()         { *m = NotificationTemplate{} }
func (m *NotificationTemplate) String() string { return proto.CompactTextString(m) }
func (*NotificationTemplate) ProtoMessage()    {}
func (*NotificationTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{20}
}

func (m *NotificationTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationTemplate.Unmarshal(m, b)
}
func (m *NotificationTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationTemplate.Marshal(b, m, deterministic)
}
func (m *NotificationTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationTemplate.Merge(m, src)
}
func (m *NotificationTemplate) XXX_Size() int {
	return xxx_messageInfo_NotificationTemplate.Size(m)
}
func (m *NotificationTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationTemplate proto.InternalMessageInfo

func (m *NotificationTemplate) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NotificationTemplate) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *NotificationTemplate) GetNotificationType() string {
	if m != nil {
		return m.NotificationType
	}
	return ""
}

func (m *NotificationTemplate) GetTemplate() string {
	if m != nil {
		return m.Template
	}
	return ""
}

func (m *NotificationTemplate) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *NotificationTemplate) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *NotificationTemplate) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *NotificationTemplate) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *NotificationTemplate) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

type NotificationList struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceType          string   `protobuf:"bytes,2,opt,name=serviceType,proto3" json:"serviceType,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	IsReadAt             string   `protobuf:"bytes,4,opt,name=isReadAt,proto3" json:"isReadAt,omitempty"`
	SenderId             string   `protobuf:"bytes,5,opt,name=senderId,proto3" json:"senderId,omitempty"`
	RecipientId          string   `protobuf:"bytes,6,opt,name=recipientId,proto3" json:"recipientId,omitempty"`
	CompanyId            string   `protobuf:"bytes,7,opt,name=companyId,proto3" json:"companyId,omitempty"`
	CreatedAt            string   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy            string   `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy            string   `protobuf:"bytes,11,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationList) Reset()         { *m = NotificationList{} }
func (m *NotificationList) String() string { return proto.CompactTextString(m) }
func (*NotificationList) ProtoMessage()    {}
func (*NotificationList) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{21}
}

func (m *NotificationList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationList.Unmarshal(m, b)
}
func (m *NotificationList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationList.Marshal(b, m, deterministic)
}
func (m *NotificationList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationList.Merge(m, src)
}
func (m *NotificationList) XXX_Size() int {
	return xxx_messageInfo_NotificationList.Size(m)
}
func (m *NotificationList) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationList.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationList proto.InternalMessageInfo

func (m *NotificationList) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NotificationList) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *NotificationList) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *NotificationList) GetIsReadAt() string {
	if m != nil {
		return m.IsReadAt
	}
	return ""
}

func (m *NotificationList) GetSenderId() string {
	if m != nil {
		return m.SenderId
	}
	return ""
}

func (m *NotificationList) GetRecipientId() string {
	if m != nil {
		return m.RecipientId
	}
	return ""
}

func (m *NotificationList) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func (m *NotificationList) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *NotificationList) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *NotificationList) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *NotificationList) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

type NotificationRetry struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceType          string   `protobuf:"bytes,2,opt,name=serviceType,proto3" json:"serviceType,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	RetryCount           int32    `protobuf:"varint,4,opt,name=retryCount,proto3" json:"retryCount,omitempty"`
	SenderId             string   `protobuf:"bytes,5,opt,name=senderId,proto3" json:"senderId,omitempty"`
	RecipientId          string   `protobuf:"bytes,6,opt,name=recipientId,proto3" json:"recipientId,omitempty"`
	CcId                 string   `protobuf:"bytes,7,opt,name=ccId,proto3" json:"ccId,omitempty"`
	CompanyId            string   `protobuf:"bytes,8,opt,name=companyId,proto3" json:"companyId,omitempty"`
	CreatedAt            string   `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy            string   `protobuf:"bytes,10,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy            string   `protobuf:"bytes,12,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationRetry) Reset()         { *m = NotificationRetry{} }
func (m *NotificationRetry) String() string { return proto.CompactTextString(m) }
func (*NotificationRetry) ProtoMessage()    {}
func (*NotificationRetry) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{22}
}

func (m *NotificationRetry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationRetry.Unmarshal(m, b)
}
func (m *NotificationRetry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationRetry.Marshal(b, m, deterministic)
}
func (m *NotificationRetry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationRetry.Merge(m, src)
}
func (m *NotificationRetry) XXX_Size() int {
	return xxx_messageInfo_NotificationRetry.Size(m)
}
func (m *NotificationRetry) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationRetry.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationRetry proto.InternalMessageInfo

func (m *NotificationRetry) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NotificationRetry) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *NotificationRetry) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *NotificationRetry) GetRetryCount() int32 {
	if m != nil {
		return m.RetryCount
	}
	return 0
}

func (m *NotificationRetry) GetSenderId() string {
	if m != nil {
		return m.SenderId
	}
	return ""
}

func (m *NotificationRetry) GetRecipientId() string {
	if m != nil {
		return m.RecipientId
	}
	return ""
}

func (m *NotificationRetry) GetCcId() string {
	if m != nil {
		return m.CcId
	}
	return ""
}

func (m *NotificationRetry) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func (m *NotificationRetry) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *NotificationRetry) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *NotificationRetry) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *NotificationRetry) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

type NotificationGroupParam struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	OrgID                string   `protobuf:"bytes,4,opt,name=orgID,proto3" json:"orgID,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy            string   `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy            string   `protobuf:"bytes,8,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationGroupParam) Reset()         { *m = NotificationGroupParam{} }
func (m *NotificationGroupParam) String() string { return proto.CompactTextString(m) }
func (*NotificationGroupParam) ProtoMessage()    {}
func (*NotificationGroupParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{23}
}

func (m *NotificationGroupParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationGroupParam.Unmarshal(m, b)
}
func (m *NotificationGroupParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationGroupParam.Marshal(b, m, deterministic)
}
func (m *NotificationGroupParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationGroupParam.Merge(m, src)
}
func (m *NotificationGroupParam) XXX_Size() int {
	return xxx_messageInfo_NotificationGroupParam.Size(m)
}
func (m *NotificationGroupParam) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationGroupParam.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationGroupParam proto.InternalMessageInfo

func (m *NotificationGroupParam) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NotificationGroupParam) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NotificationGroupParam) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *NotificationGroupParam) GetOrgID() string {
	if m != nil {
		return m.OrgID
	}
	return ""
}

func (m *NotificationGroupParam) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *NotificationGroupParam) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *NotificationGroupParam) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *NotificationGroupParam) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

type NotificationLog struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ServiceType          string   `protobuf:"bytes,2,opt,name=serviceType,proto3" json:"serviceType,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Product              string   `protobuf:"bytes,5,opt,name=product,proto3" json:"product,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy            string   `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy            string   `protobuf:"bytes,9,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	OrgID                string   `protobuf:"bytes,10,opt,name=orgID,proto3" json:"orgID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationLog) Reset()         { *m = NotificationLog{} }
func (m *NotificationLog) String() string { return proto.CompactTextString(m) }
func (*NotificationLog) ProtoMessage()    {}
func (*NotificationLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{24}
}

func (m *NotificationLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationLog.Unmarshal(m, b)
}
func (m *NotificationLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationLog.Marshal(b, m, deterministic)
}
func (m *NotificationLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationLog.Merge(m, src)
}
func (m *NotificationLog) XXX_Size() int {
	return xxx_messageInfo_NotificationLog.Size(m)
}
func (m *NotificationLog) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationLog.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationLog proto.InternalMessageInfo

func (m *NotificationLog) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *NotificationLog) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *NotificationLog) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *NotificationLog) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *NotificationLog) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *NotificationLog) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *NotificationLog) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *NotificationLog) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *NotificationLog) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *NotificationLog) GetOrgID() string {
	if m != nil {
		return m.OrgID
	}
	return ""
}

func init() {
	proto.RegisterType((*EditNotificationPermissionParam)(nil), "proto.EditNotificationPermissionParam")
	proto.RegisterType((*NotificationServiceTypePermissionParam)(nil), "proto.NotificationServiceTypePermissionParam")
	proto.RegisterType((*NotificationPermissionRecipientsParam)(nil), "proto.NotificationPermissionRecipientsParam")
	proto.RegisterType((*NotificationRequest)(nil), "proto.NotificationRequest")
	proto.RegisterType((*NotificationGroupMemberParam)(nil), "proto.NotificationGroupMemberParam")
	proto.RegisterType((*NotificationGroupListParam)(nil), "proto.NotificationGroupListParam")
	proto.RegisterType((*NotificationPermissionListParam)(nil), "proto.NotificationPermissionListParam")
	proto.RegisterType((*NotificationLogListParam)(nil), "proto.NotificationLogListParam")
	proto.RegisterType((*LogListDateRange)(nil), "proto.LogListDateRange")
	proto.RegisterType((*NotificationContentRequest)(nil), "proto.NotificationContentRequest")
	proto.RegisterType((*SendNotificationRequest)(nil), "proto.SendNotificationRequest")
	proto.RegisterType((*NotificationResponse)(nil), "proto.NotificationResponse")
	proto.RegisterType((*NotificationListResponse)(nil), "proto.NotificationListResponse")
	proto.RegisterType((*NotificationGroupList)(nil), "proto.NotificationGroupList")
	proto.RegisterType((*NotificationGroupMemberList)(nil), "proto.NotificationGroupMemberList")
	proto.RegisterType((*NotificationPermissionList)(nil), "proto.NotificationPermissionList")
	proto.RegisterType((*NotificationServiceTypePermission)(nil), "proto.NotificationServiceTypePermission")
	proto.RegisterType((*NotificationProductPermission)(nil), "proto.NotificationProductPermission")
	proto.RegisterType((*NotificationPermissionRecipients)(nil), "proto.NotificationPermissionRecipients")
	proto.RegisterType((*NotificationPermissionRecipientUsers)(nil), "proto.NotificationPermissionRecipientUsers")
	proto.RegisterType((*NotificationTemplate)(nil), "proto.NotificationTemplate")
	proto.RegisterType((*NotificationList)(nil), "proto.NotificationList")
	proto.RegisterType((*NotificationRetry)(nil), "proto.NotificationRetry")
	proto.RegisterType((*NotificationGroupParam)(nil), "proto.NotificationGroupParam")
	proto.RegisterType((*NotificationLog)(nil), "proto.NotificationLog")
}

func init() { proto.RegisterFile("notification.proto", fileDescriptor_736a457d4a5efa07) }

var fileDescriptor_736a457d4a5efa07 = []byte{
	// 1521 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x59, 0xcd, 0x6e, 0xdb, 0xc6,
	0x13, 0xff, 0x8b, 0xb2, 0xbe, 0x46, 0xf9, 0x27, 0xce, 0xc6, 0xb1, 0x09, 0xd9, 0x8e, 0x15, 0x36,
	0x4d, 0x8d, 0xa6, 0x4d, 0x0b, 0xa5, 0xed, 0xb1, 0x80, 0x63, 0xb5, 0x86, 0x82, 0xc4, 0x09, 0x36,
	0x1f, 0x68, 0x92, 0x36, 0x01, 0x4d, 0xae, 0x5d, 0x36, 0x12, 0xa9, 0x90, 0xab, 0x00, 0xba, 0xf4,
	0xd6, 0x47, 0xe8, 0xa5, 0x97, 0xa2, 0x97, 0xa2, 0xef, 0xd1, 0x37, 0xe8, 0xb9, 0x6f, 0xd0, 0x4b,
	0x9e, 0xa0, 0x28, 0xf6, 0x8b, 0x5c, 0x52, 0x24, 0xa5, 0x5a, 0x06, 0x7a, 0x32, 0x67, 0x67, 0xf6,
	0x37, 0xbb, 0xbf, 0x9d, 0x9d, 0xd9, 0x91, 0x01, 0xf9, 0x01, 0xf5, 0x8e, 0x3d, 0xc7, 0xa6, 0x5e,
	0xe0, 0xdf, 0x1c, 0x87, 0x01, 0x0d, 0x50, 0x8d, 0xff, 0xe9, 0x80, 0x13, 0x84, 0x44, 0x0c, 0x59,
	0x3f, 0x19, 0xb0, 0xf3, 0x85, 0xeb, 0xd1, 0x43, 0xcd, 0xfa, 0x01, 0x09, 0x47, 0x5e, 0x14, 0xb1,
	0x2f, 0x3b, 0xb4, 0x47, 0xe8, 0x3c, 0x18, 0x83, 0xbe, 0x59, 0xe9, 0x56, 0x76, 0x5b, 0xd8, 0x18,
	0xf4, 0xd1, 0xfb, 0xb0, 0xaa, 0x83, 0x3f, 0x9a, 0x8e, 0x89, 0x69, 0x70, 0xed, 0xcc, 0x38, 0xba,
	0x0f, 0xed, 0x88, 0x84, 0x6f, 0x3c, 0x87, 0x70, 0xb3, 0x6a, 0xb7, 0xba, 0xdb, 0xee, 0x7d, 0x28,
	0x9c, 0xdf, 0xd4, 0x9d, 0x3e, 0x4c, 0xac, 0x32, 0xfe, 0xb1, 0x8e, 0x80, 0xb6, 0xa0, 0x35, 0x0e,
	0x03, 0x77, 0xe2, 0xd0, 0x41, 0xdf, 0x5c, 0xe1, 0x5e, 0x93, 0x01, 0x74, 0x17, 0x20, 0x24, 0x8e,
	0x37, 0xf6, 0x88, 0x4f, 0x23, 0xb3, 0xd6, 0xad, 0xec, 0xb6, 0x7b, 0x1f, 0xe4, 0x78, 0x4b, 0x5c,
	0xe0, 0xd8, 0x5c, 0x38, 0xd3, 0xe6, 0x5b, 0x2f, 0xe0, 0xfa, 0x62, 0x4b, 0x44, 0x08, 0x56, 0x28,
	0xdb, 0x9f, 0x20, 0x89, 0x7f, 0xa3, 0x2e, 0xb4, 0xbd, 0xe8, 0x9e, 0xed, 0xbb, 0x36, 0x0d, 0xc2,
	0x29, 0x67, 0xa8, 0x89, 0xf5, 0x21, 0xeb, 0x21, 0xbc, 0xbb, 0xd0, 0xa2, 0xd0, 0x1a, 0xd4, 0x26,
	0x11, 0x09, 0x23, 0xb3, 0xd2, 0xad, 0xee, 0xb6, 0xb0, 0x10, 0xd8, 0xe8, 0x49, 0x18, 0x4c, 0xc6,
	0x92, 0x7c, 0x21, 0x58, 0x3f, 0x36, 0xe0, 0x92, 0x8e, 0x8a, 0xc9, 0xeb, 0x09, 0x89, 0x28, 0xfa,
	0x0a, 0x36, 0x22, 0xe2, 0xbb, 0x39, 0x2a, 0xbe, 0xea, 0x76, 0xef, 0x8a, 0xe4, 0xe9, 0x61, 0xbe,
	0x15, 0x2e, 0x9a, 0x8e, 0xee, 0xc3, 0x5a, 0xea, 0xdc, 0xc9, 0x68, 0x3c, 0xb4, 0xa9, 0x88, 0x89,
	0x76, 0x6f, 0x33, 0x87, 0x7e, 0x65, 0x82, 0x73, 0x27, 0xa2, 0xfd, 0x74, 0x80, 0xdd, 0xf5, 0x22,
	0x6a, 0x56, 0x39, 0xd8, 0x46, 0x0e, 0x18, 0x53, 0xe3, 0x99, 0x09, 0xe8, 0x4b, 0xb8, 0xe8, 0xa7,
	0x16, 0x4b, 0xc3, 0x29, 0x0f, 0x98, 0x76, 0xcf, 0xcc, 0x41, 0xe1, 0x7a, 0x3c, 0x3b, 0x05, 0x3d,
	0x86, 0x75, 0x7d, 0xf0, 0x80, 0x91, 0xcc, 0x4f, 0x45, 0x86, 0xd7, 0x76, 0x0e, 0x58, 0x62, 0x84,
	0x0b, 0x26, 0xa3, 0x13, 0xd8, 0x9a, 0xd1, 0xdc, 0x23, 0xa3, 0x23, 0x12, 0x0a, 0xf0, 0x3a, 0x07,
	0x7f, 0xa7, 0x08, 0x5c, 0x33, 0xc5, 0xa5, 0x40, 0xe8, 0x45, 0x7a, 0xfd, 0x49, 0x90, 0x99, 0x0d,
	0xee, 0xe2, 0xba, 0x74, 0x31, 0x27, 0x0b, 0xe0, 0x02, 0x14, 0x74, 0x0c, 0x9d, 0x7c, 0x0d, 0x3f,
	0xb6, 0x66, 0xca, 0xc7, 0x61, 0xa1, 0xa1, 0xf0, 0x51, 0x82, 0x84, 0x9e, 0x83, 0x99, 0x3a, 0xe3,
	0xe0, 0x24, 0x9e, 0x67, 0xb6, 0xb8, 0x97, 0x9d, 0xbc, 0xe0, 0xd0, 0xcc, 0x70, 0x21, 0x00, 0xb2,
	0xd3, 0x9b, 0xe0, 0x24, 0x26, 0xf0, 0xc0, 0xe1, 0xaf, 0x16, 0x9d, 0x45, 0xc1, 0xfa, 0xd3, 0x3a,
	0xeb, 0xcf, 0x0a, 0x6c, 0x95, 0x1d, 0x23, 0x4b, 0xb3, 0x9e, 0xab, 0xd2, 0xac, 0xe7, 0x22, 0x13,
	0x1a, 0xfc, 0x46, 0x0f, 0xfa, 0xf2, 0x82, 0x2b, 0x11, 0xad, 0x43, 0x9d, 0x65, 0x80, 0x41, 0x9f,
	0xe7, 0xd3, 0x16, 0x96, 0x12, 0xda, 0x06, 0x70, 0x42, 0x62, 0x53, 0xe2, 0xbe, 0xb4, 0xa9, 0x4a,
	0x8e, 0x72, 0x64, 0x8f, 0xea, 0xea, 0xa3, 0x29, 0x8f, 0xde, 0x44, 0x7d, 0x7b, 0xca, 0xd4, 0x93,
	0xb1, 0xab, 0x66, 0xd7, 0x85, 0x5a, 0x8e, 0x88, 0xd9, 0x4a, 0x7d, 0x34, 0xe5, 0xb1, 0x93, 0xa8,
	0x6f, 0x4f, 0xad, 0xef, 0xa1, 0x53, 0x4c, 0x0c, 0xcb, 0x8f, 0x63, 0xfb, 0x44, 0xe4, 0xc7, 0x1a,
	0xe6, 0xdf, 0x2c, 0x7d, 0x0d, 0xbd, 0x91, 0x47, 0xf9, 0xee, 0x6a, 0x58, 0x08, 0xfa, 0xae, 0xab,
	0xe9, 0x5d, 0x6f, 0x41, 0x8b, 0x7f, 0x1e, 0xda, 0x23, 0xa2, 0x36, 0x17, 0x0f, 0x58, 0xb7, 0x60,
	0x67, 0x4e, 0x74, 0xa1, 0x55, 0xa8, 0xbe, 0x22, 0x53, 0xc9, 0x30, 0xfb, 0xb4, 0x7e, 0xae, 0x80,
	0x59, 0x14, 0x2d, 0x6c, 0x25, 0xb2, 0xb0, 0xc8, 0x29, 0x4a, 0x64, 0x1a, 0xe7, 0x5b, 0xdb, 0xf7,
	0xc9, 0x50, 0x9d, 0x8c, 0x14, 0xb9, 0x26, 0xf0, 0x29, 0xf1, 0xa9, 0x5a, 0xbd, 0x14, 0xd1, 0xa7,
	0xd0, 0x62, 0x54, 0x85, 0xb6, 0x7f, 0x42, 0x64, 0x1a, 0x52, 0xc9, 0x4c, 0x7a, 0xed, 0xb3, 0x84,
	0xc8, 0xd4, 0x38, 0xb1, 0xb4, 0x3e, 0x83, 0xd5, 0xac, 0x9a, 0x91, 0x79, 0x1c, 0x06, 0x23, 0x55,
	0x6c, 0xd8, 0x37, 0x0b, 0x1e, 0x1a, 0xc8, 0xd5, 0x18, 0x34, 0xb0, 0xfa, 0xe9, 0xe3, 0xd8, 0x17,
	0xab, 0x50, 0x19, 0x7b, 0x86, 0x09, 0x76, 0x18, 0x6f, 0xec, 0xe1, 0x44, 0x15, 0x72, 0x21, 0x58,
	0x6f, 0x0d, 0xd8, 0x28, 0x28, 0x07, 0xe9, 0x42, 0x5c, 0xc9, 0x16, 0xe2, 0x6e, 0xba, 0xee, 0x0b,
	0xd4, 0x54, 0x21, 0xcf, 0x7b, 0x45, 0x54, 0x0b, 0x5e, 0x11, 0x62, 0x77, 0x2b, 0x3c, 0xd8, 0x0d,
	0x1a, 0x30, 0xd9, 0x71, 0xcc, 0x9a, 0x90, 0x1d, 0x07, 0x1d, 0xc0, 0xff, 0x5f, 0x91, 0xe9, 0x13,
	0x7b, 0x28, 0xf7, 0x69, 0xd6, 0xf9, 0x3b, 0x23, 0xef, 0xc6, 0xa6, 0x99, 0xc0, 0xe9, 0x79, 0xfa,
	0xf9, 0x35, 0xd2, 0xe7, 0xa7, 0x48, 0x6f, 0x6a, 0xa4, 0x7f, 0x02, 0x6d, 0xa9, 0xe6, 0xab, 0x67,
	0x59, 0xe8, 0x7c, 0x0f, 0x49, 0xa7, 0xfb, 0x89, 0x06, 0xeb, 0x66, 0x8c, 0x38, 0x1a, 0xda, 0xce,
	0x2b, 0x7e, 0x81, 0x41, 0x10, 0x17, 0x0f, 0x58, 0x07, 0xb0, 0x96, 0x66, 0x3b, 0x1a, 0x07, 0x7e,
	0x44, 0xd0, 0x47, 0xd0, 0x0c, 0xe5, 0xb7, 0xac, 0xd7, 0x97, 0x94, 0xa3, 0x70, 0xe2, 0x2a, 0x33,
	0x1c, 0x1b, 0x59, 0x7f, 0x1b, 0x99, 0xd8, 0x66, 0x65, 0x52, 0xa1, 0xdd, 0x80, 0x26, 0xbb, 0x83,
	0x03, 0xff, 0x38, 0x90, 0x68, 0x17, 0x24, 0xda, 0x03, 0x39, 0x8c, 0x63, 0x03, 0x34, 0x80, 0xf3,
	0xe3, 0x74, 0x56, 0x37, 0x0a, 0xe9, 0x4d, 0xdf, 0x3b, 0x9c, 0x99, 0x88, 0x3e, 0x86, 0xc6, 0x50,
	0x84, 0xb3, 0x7c, 0x0a, 0xae, 0xe7, 0xe7, 0x6c, 0xac, 0xcc, 0x10, 0x86, 0xcb, 0xb9, 0x49, 0x95,
	0x47, 0x43, 0xbb, 0xb7, 0x55, 0x96, 0x94, 0x71, 0xfe, 0x54, 0xe4, 0xc2, 0x66, 0x41, 0xc9, 0xe4,
	0xc8, 0x35, 0x8e, 0x6c, 0x95, 0x97, 0x5e, 0x8e, 0x5f, 0x06, 0x63, 0x7d, 0x03, 0x97, 0x73, 0x57,
	0x35, 0xf3, 0x9e, 0x46, 0xb0, 0xe2, 0xb3, 0x9c, 0x26, 0x2e, 0x09, 0xff, 0x66, 0xf7, 0xc7, 0x25,
	0x91, 0x13, 0x7a, 0x63, 0x36, 0x57, 0x5e, 0x0c, 0x7d, 0xc8, 0x7a, 0x0d, 0x9b, 0x25, 0x4b, 0x9b,
	0x71, 0x52, 0x5c, 0x4d, 0x94, 0xfb, 0xaa, 0xe6, 0x7e, 0x0d, 0x6a, 0x64, 0x64, 0x7b, 0x43, 0x99,
	0x67, 0x85, 0x60, 0xfd, 0x6e, 0xa4, 0xb3, 0x4a, 0xa6, 0x42, 0x2f, 0xd3, 0x27, 0xdc, 0xc9, 0xeb,
	0x13, 0x76, 0x17, 0xed, 0x13, 0xd2, 0x99, 0xe5, 0xf3, 0x24, 0x71, 0x8b, 0x44, 0x7b, 0x2d, 0x2f,
	0x50, 0x85, 0x85, 0x86, 0x11, 0xa7, 0xf7, 0x83, 0x9c, 0x26, 0xe2, 0xbd, 0x05, 0x9b, 0x08, 0xbd,
	0x7f, 0x60, 0x2c, 0x06, 0xe1, 0xc9, 0xa0, 0x2f, 0x8b, 0xa9, 0x10, 0xac, 0xa7, 0x70, 0x75, 0xee,
	0x86, 0x4e, 0xd9, 0x50, 0xbc, 0x84, 0xed, 0xd2, 0x3d, 0xce, 0x4f, 0xda, 0x52, 0x38, 0x4c, 0xe2,
	0x51, 0x1f, 0xb2, 0x7e, 0xab, 0x40, 0x77, 0x1e, 0x05, 0x68, 0x4f, 0xef, 0x56, 0xda, 0xbd, 0x1b,
	0x8b, 0x51, 0xf7, 0x98, 0x4d, 0x51, 0xad, 0xcd, 0x9e, 0xde, 0xda, 0xfc, 0x5b, 0x08, 0xd1, 0x07,
	0xdd, 0x81, 0x6b, 0x8b, 0x98, 0x2f, 0x72, 0x1b, 0xad, 0x5f, 0x8d, 0x74, 0x56, 0x8e, 0x3b, 0x95,
	0xec, 0x9b, 0xed, 0x6c, 0xcb, 0x5e, 0x07, 0x9a, 0x54, 0x35, 0x53, 0xe2, 0x22, 0xc6, 0x32, 0xbb,
	0xcf, 0xd1, 0xe4, 0xe8, 0x3b, 0xe2, 0x50, 0xf9, 0x92, 0x53, 0x62, 0xe6, 0x15, 0x58, 0x2f, 0x7f,
	0x05, 0x36, 0xca, 0x5f, 0x81, 0xcd, 0xf2, 0x57, 0x60, 0x2b, 0xfb, 0x0a, 0xfc, 0xc3, 0x80, 0xd5,
	0x6c, 0xd1, 0x39, 0x05, 0x49, 0xc5, 0xcf, 0xa8, 0x0e, 0x34, 0xbd, 0x08, 0x13, 0xdb, 0xdd, 0x53,
	0x0f, 0xdc, 0x58, 0x66, 0x3a, 0xd6, 0xa2, 0x92, 0x70, 0xe0, 0x4a, 0x4e, 0x62, 0x99, 0xf9, 0x8c,
	0x2f, 0xe6, 0xc0, 0x95, 0xac, 0xe8, 0x43, 0xec, 0x6a, 0x38, 0xc1, 0x68, 0x6c, 0xfb, 0xd3, 0x81,
	0x1b, 0xd3, 0xa2, 0x06, 0x32, 0xa4, 0x36, 0xcb, 0x49, 0x6d, 0x95, 0x93, 0x0a, 0xe5, 0xa4, 0xb6,
	0xb3, 0xa4, 0xfe, 0x65, 0xc0, 0xc5, 0x99, 0x56, 0xf5, 0x4c, 0x59, 0xbd, 0xc2, 0x32, 0x1e, 0x0d,
	0xa7, 0xfb, 0xc1, 0xc4, 0x17, 0xbc, 0xd6, 0xb0, 0x36, 0xb2, 0x24, 0xb3, 0x08, 0x56, 0x1c, 0x27,
	0x26, 0x95, 0x7f, 0xa7, 0xd9, 0x6e, 0x96, 0xb3, 0xdd, 0x2a, 0x67, 0x1b, 0xca, 0xd9, 0x6e, 0x97,
	0xb3, 0x7d, 0x2e, 0xcb, 0xf6, 0xdb, 0x0a, 0xac, 0xe7, 0xf7, 0xf2, 0x33, 0x94, 0x9f, 0xaa, 0x70,
	0x27, 0x55, 0x61, 0x45, 0xab, 0x0a, 0x99, 0x2d, 0xd7, 0xca, 0xb7, 0x5c, 0x2f, 0xdf, 0x72, 0xa3,
	0x7c, 0xcb, 0xcd, 0xec, 0x96, 0x7f, 0x31, 0xe0, 0x42, 0xe6, 0x01, 0x36, 0x93, 0x16, 0x97, 0x09,
	0xaf, 0x75, 0xa8, 0x47, 0xd4, 0xa6, 0x93, 0x48, 0x6e, 0x59, 0x4a, 0x7a, 0x87, 0x55, 0x4b, 0x77,
	0x58, 0xff, 0x61, 0x0e, 0x4b, 0xce, 0x07, 0xb4, 0xf3, 0xe9, 0xfd, 0xd0, 0x80, 0x73, 0x3a, 0x47,
	0xe8, 0x11, 0x6c, 0xec, 0x73, 0x8f, 0x33, 0xc1, 0x82, 0x3a, 0xb9, 0xbf, 0x2f, 0xf1, 0x86, 0xa3,
	0xb3, 0x99, 0xab, 0x93, 0x6f, 0xf6, 0xff, 0xa1, 0x67, 0xb0, 0x5d, 0x80, 0x2a, 0xde, 0x76, 0xcb,
	0x60, 0xdf, 0x83, 0xd5, 0x6c, 0x33, 0xb7, 0x0c, 0xdc, 0x53, 0xd8, 0x7a, 0xcc, 0x49, 0xcb, 0x2f,
	0xb3, 0xcb, 0x40, 0x3f, 0x82, 0x8d, 0x3e, 0x19, 0x92, 0xb3, 0xe7, 0xb6, 0x00, 0x75, 0x79, 0x6e,
	0x9f, 0x43, 0x87, 0xd5, 0xba, 0x53, 0x50, 0xb1, 0x53, 0xf4, 0x93, 0xa6, 0x4e, 0xc7, 0xa5, 0x2c,
	0x38, 0xbb, 0xa2, 0x4b, 0xa2, 0x3e, 0x81, 0xcb, 0x59, 0xd4, 0xf9, 0x14, 0x2f, 0x80, 0xfb, 0x35,
	0x6c, 0xe6, 0xe2, 0x2e, 0x40, 0xf2, 0x7c, 0xf4, 0xdb, 0x8d, 0x67, 0xe2, 0xbf, 0x18, 0x47, 0x75,
	0xfe, 0xe7, 0xd6, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc6, 0x28, 0x00, 0x20, 0xe9, 0x18, 0x00,
	0x00,
}
