// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	client "github.com/micro/go-micro/v2/client"
	commonproto "github.com/zebraxid/common-services-proto"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AuditTrailService is an autogenerated mock type for the AuditTrailService type
type AuditTrailService struct {
	mock.Mock
}

// ReadLog provides a mock function with given fields: ctx, in, opts
func (_m *AuditTrailService) ReadLog(ctx context.Context, in *commonproto.ReadLogRequest, opts ...client.CallOption) (*commonproto.AuditResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *commonproto.AuditResponse
	if rf, ok := ret.Get(0).(func(context.Context, *commonproto.ReadLogRequest, ...client.CallOption) *commonproto.AuditResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonproto.AuditResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *commonproto.ReadLogRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendBulkLog provides a mock function with given fields: ctx, in, opts
func (_m *AuditTrailService) SendBulkLog(ctx context.Context, in *commonproto.SendLogRequest, opts ...client.CallOption) (*commonproto.AuditResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *commonproto.AuditResponse
	if rf, ok := ret.Get(0).(func(context.Context, *commonproto.SendLogRequest, ...client.CallOption) *commonproto.AuditResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonproto.AuditResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *commonproto.SendLogRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendLog provides a mock function with given fields: ctx, in, opts
func (_m *AuditTrailService) SendLog(ctx context.Context, in *commonproto.SendLogRequest, opts ...client.CallOption) (*commonproto.AuditResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *commonproto.AuditResponse
	if rf, ok := ret.Get(0).(func(context.Context, *commonproto.SendLogRequest, ...client.CallOption) *commonproto.AuditResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonproto.AuditResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *commonproto.SendLogRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
